export default {
  list: 'POST /worksheet/list',
  close: 'POST /worksheet/close',
  details: 'POST /worksheet/detail',
  conversations: 'POST /im-server/conversation/find',
  statusCount: 'POST /worksheet/get-status-count',
  getRelations: 'POST /worksheet/relation',
  addRecord: 'POST /worksheet/detail-add-record',
  addRelation: 'POST /worksheet/add-relation',
  getServiceList: 'POST /im/get-customer-service-list',
  transfer: 'POST /worksheet/transfer',
  getTypeList: 'POST /worksheet-type/list',
  deleteTypes: 'POST /worksheet-type/delete',
  addEditTypes: 'POST /worksheet-type/add',
}